version: '3.7'
services:
    # mailer:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     command: 'php artisan serve --host=0.0.0.0'
    #     volumes:
    #         - .:/app
    #     ports:
    #         - 8000:8000
    #     depends_on:
    #         - db
    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on:
            - db
    db:
        platform: linux/x86_64
        image: mysql:latest
        environment:
            MYSQL_DATABASE: mailer-db
            MYSQL_USER: user
            MYSQL_ROOT: root
            MYSQL_PASSWORD: zaq1@WSX
            MYSQL_ROOT_PASSWORD: zaq1@WSX
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
